version: '3'
services:
    python:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        volumes:
            - ../:/app
        working_dir: /app
        tty: true
